# Get the LCI data of a list of macs
string[] mac_list  # a list of macs to be queried
---
# An array containing LCIData record for each requested mac
LCIData[] lci_data_list
---
# The feedback contains the LCI data for each entry in the query list
LCIData lci_data
uint8 STATUS_SUCCESS = 0
uint8 STATUS_INVALID_MAC = 1
uint8 STATUS_INVALID_LCI = 2
uint8 STATUS_HAS_NO_LCI = 3
uint8 STATUS_INTERNAL_ERROR = 4
uint8 status
