# This service enables configuring the list of FTM Devices with which to perform FTM range measurements
string[] mac_list  # a list of macs addresses of devices with FTM capabilities
---
uint8 STATUS_SUCCESS = 0
uint8 STATUS_INVALID_MAC = 1
uint8 status
